### ISSUE TITLE
issue pairing the Nintendo Switch with my Raspberry pi 3

### ISSUE THREAD

**Issue by aslaue** [Aodrulez/SwitchX#1]
Hi!
I'm interested to connect with the help of your project my nintendo switch with my Raspberry PI 3 and a wired Xbox one controller of the mark Afterglow, but the pairing between the NS and the RPI3 doesn't seem to work
I've followed your step, that is copying the github folder in the /home/pi/ directory, then I typed in the command:
'cd SwitchX-master/'
'sudo python setup.py'
It seems to have installed correctly. I've then checked that the Bluetooth was on, then I typed the command
'sudo reboot'
But once the RPI has finished boot, it doesn't seem to connect to the Nintendo Switch. I put the 2 devices next to each other, and put the NS in the connection of remote menu, but even after 10 min, there is no pairing.
You didn't mention it in the video or the github webpage, but, is it right that there is no need for any other piece of hardware for the connection between the NS and the RPI 3 ?
Also I didn't see anywhere if there was a command to run after the installation and the boot. In any case, I didn't see that the installation had put anything new on the crontab, and the command 'ps -e' does not display anything that could be associated with xswitch, which is a bit weird.
Could you help me ? Is there anything that I did wrong ? Or may a previous update have messed up this functionality ? (I'm running the version 11.0.1 on my NS)
Thanks for your help
Alexandre

**Comment by Aodrulez** [comment]
Hi Aslaue,

You are right, there's no physical connection required between the Switch & RPi. Once this script is properly setup, it uses a command known as "supervisor" to run at each boot. You should still be able to the see the script running if you look at active processes though. Do let me know if you still haven't got this working.
